### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by lireo** [raeslab/GMMs#1]
Hello,

I can't run your app. 
I have an error with log4j, the beginning of error message is : 

> JarClassLoader: Warning: Null manifest from input stream associated with: lib/jdmp-0.1.1.jar
> JarClassLoader: Warning: Null manifest from input stream associated with: lib/aspectjweaver-1.6.12.jar
> JarClassLoader: Warning: Null manifest from input stream associated with: lib/javax.inject-1.jar
> log4j:ERROR Could not parse url [jar:file:/gmms.jar!/lib/BSB-Utils-1.0-alpha-1-SNAPSHOT.jar!/log4j.xml].
> java.io.FileNotFoundException: /gmms.jar (No such file or directory)

And my command line is : 

> java -jar gmms.jar 1 median GMMs.v1.07.txt ../input/ ../output/

I would appreciate your help.
Thanks.

Aurélie

**Comment by raeslab** [comment]
Hi Aurélie,

This is only a log4j issue, meaning the logging system is not properly setup.
The app works fine and you should see the result in ../output.

Please let me know if it is not the case.
cheers,
Youssef

**Comment by joshgraymd** [comment]
I'm having the same issue.
