### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by joshgraymd** [raeslab/GMMs#2]
Hello,

I can't run your app.
I have an error with log4j, the beginning of error message is :

JarClassLoader: Warning: Null manifest from input stream associated with: lib/jdmp-0.1.1.jar
JarClassLoader: Warning: Null manifest from input stream associated with: lib/aspectjweaver-1.6.12.jar
JarClassLoader: Warning: Null manifest from input stream associated with: lib/javax.inject-1.jar
log4j:ERROR Could not parse url [jar:file:///Users/joshg/Downloads/test_jar/gmms.jar!/lib/BSB-Utils-1.0-alpha-1-SNAPSHOT.jar!/log4j.xml].
java.io.FileNotFoundException: JAR entry lib/BSB-Utils-1.0-alpha-1-SNAPSHOT.jar!/log4j.xml not found in /Users/joshg/Downloads/test_jar/gmms.jar
 
And my command line is :

java -jar //Users/joshg/Downloads/test_jar/gmms.jar

I would appreciate your help.
Thanks.

Josh

**Comment by omixer** [comment]
Dear Josh,

This is only a warning that the logging system is not properly configured. The tool would work properly if you run it. However, the gmms.jar is not maintained anymore (the GMMs.v1.07.txt is up to date though), and has been replaced by Omixer-RPM https://github.com/raeslab/omixer-rpm.

I hope this helps,
Kind regards,
Youssef
